#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.abspath("./lib/"))

from bunk.server import BunkServer

from settings import hosts
from settings import long_running
from settings import worker_count

import bunk_routing

# start the server
BunkServer(bunk_routing=bunk_routing, hosts=hosts, long_running=long_running, worker_count=worker_count).start()
